server:
  port: 8080
  error:
    include-message: always

spring:
  #  Configurations for datasource and connection pool
  datasource:
    url: jdbc:postgresql://localhost:5432/smoke
    username: shreyas
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  flyway:
    enabled: false
    locations: db.migration

  main:
    web-application-type: servlet